### ISSUE TITLE
getSolution errors if solution name not available/not returned

### ISSUE THREAD

**Issue by ssmiller25** [BlueMedoraPublic/vropscli#98]
If a solution is installed that does not provide a name, the following error is thown:
```
$ ./vropscli getSolution
...list of solutions...
Error: 'name'
Pass the -v flag for more verbose error messages
```
and more detailed:
```
$ ./vropscli getSolution -v
...list of solutions...
Error: 'name'
Traceback (most recent call last):
  File "vropscli.py", line 938, in <module>
  File "site-packages/fire/core.py", line 127, in Fire
  File "site-packages/fire/core.py", line 366, in _Fire
  File "site-packages/fire/core.py", line 542, in _CallCallable
  File "vropscli.py", line 604, in getSolution
KeyError: 'name'
```

**Comment by ssmiller25** [comment]
Specifically seems to be related to Blue Medora's ITM management pack, version 4.1.2214374.  This is reproducible by the internal vrops-demo system.
